from datetime import datetime
from typing import Optional

import psycopg2
from psycopg2 import Error

class PostgresDB:
    def __init__(
        self,
        host: str,
        port: int,
        database: str,
        user: str,
        password: str
    ):
        self.host = host
        self.port = port
        self.database = database
        self.user = user
        self.password = password
        self.connection = None
        self._connect()
        self._create_tables()

    def _connect(self):
        if self.connection is not None:
            try:
                self.connection.close()
            except Exception:
                pass

        self.connection = psycopg2.connect(
            host=self.host,
            port=self.port,
            database=self.database,
            user=self.user,
            password=self.password,
        )

        self.connection.autocommit = False


    def check_connection(self):
        try:
            if self.connection is None or self.connection.closed:
                self._connect()
                return

            with self.connection.cursor() as cursor:
                cursor.execute("SELECT 1")

        except (psycopg2.InterfaceError, psycopg2.OperationalError):
            self._connect()

    def _create_tables(self) -> None:
        """
        Создаёт таблицы и индексы, если они ещё не существуют.
        """
        try:
            with self.connection.cursor() as cursor:

                # =========================================================
                # games
                # =========================================================
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS games (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        base_id BIGINT NOT NULL,
                        name TEXT,
                        place TEXT,
                        date_start TIMESTAMP,
                        date_end TIMESTAMP,
                        who_added BIGINT,
                        poll BIGINT,
                        poll_id TEXT,
                        team_notified BOOLEAN DEFAULT FALSE,
                        is_festival BOOLEAN NOT NULL DEFAULT FALSE
                    );
                """)

                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS
                    idx_games_base_id
                    ON games (base_id);
                """)

                # =========================================================
                # players
                # =========================================================
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS players (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        base_id BIGINT,
                        tg_id BIGINT,
                        name TEXT,
                        surname TEXT,
                        patronymic TEXT,
                        rating DOUBLE PRECISION NOT NULL DEFAULT 0,
                        is_base BOOLEAN NOT NULL DEFAULT FALSE,
                        is_admin BOOLEAN NOT NULL DEFAULT FALSE,
                        tg_username TEXT,
                        enable_notifications BOOLEAN DEFAULT TRUE
                    );
                """)

                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS
                    idx_players_tg_id
                    ON players (tg_id);
                """)

                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS
                    idx_players_base_id
                    ON players (base_id);
                """)

                # =========================================================
                # ready_to_play
                # =========================================================
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS ready_to_play (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        game BIGINT NOT NULL,
                        player BIGINT NOT NULL,
                        ready BOOLEAN NOT NULL
                    );
                """)

                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS
                    idx_ready_to_play_game
                    ON ready_to_play (game);
                """)

                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS
                    idx_ready_to_play_player_game
                    ON ready_to_play (player, game);
                """)

            self.connection.commit()

        except Error:
            self.connection.rollback()
            raise

    def set_team_notified(self, game_base_id: int, value: bool) -> bool:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE games
                    SET team_notified = %s
                    WHERE base_id = %s
                """, (value, game_base_id))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    # =====================================================================
    # GAMES
    # =====================================================================

    def add_game(
        self,
        base_id: int,
        name: str,
        who_added: int,
        place: str,
        date_start: datetime
    ) -> bool:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO games (
                        base_id,
                        name,
                        who_added,
                        place,
                        date_start,
                        is_festival
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (
                    base_id,
                    name,
                    who_added,
                    place,
                    date_start,
                    False
                ))

            self.connection.commit()
            return True

        except Error:
            self.connection.rollback()
            return False

    def add_festival(
        self,
        base_id: int,
        name: str,
        who_added: int,
        place: str,
        date_start: datetime,
        date_end: datetime
    ) -> bool:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO games (
                        base_id,
                        name,
                        who_added,
                        place,
                        date_start,
                        date_end,
                        is_festival
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, (
                    base_id,
                    name,
                    who_added,
                    place,
                    date_start,
                    date_end,
                    True
                ))

            self.connection.commit()
            return True

        except Error:
            self.connection.rollback()
            return False

    def add_place_for_game(self, id: int, place: str) -> bool:
        """
        Устанавливает место проведения игры.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE games
                    SET place = %s
                    WHERE base_id = %s
                """, (place, id))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    def add_dates_for_game(
        self,
        id: int,
        date_start: datetime,
        date_end: Optional[datetime] = None
    ) -> bool:
        """
        Устанавливает дату и время проведения игры.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                if date_end:
                    cursor.execute("""
                        UPDATE games
                        SET "date_start" = %s, date_end = %s
                        WHERE base_id = %s
                    """, (date_start, date_end, id))
                else:
                    cursor.execute("""
                        UPDATE games
                        SET "date_start" = %s
                        WHERE base_id = %s
                    """, (date_start, id))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    def delete_game(
            self,
            id: int
        ) -> bool:
            """
            Устанавливает дату и время проведения игры.
            """
            try:
                self.check_connection()
                with self.connection.cursor() as cursor:

                    cursor.execute("""
                        DELETE FROM games
                        WHERE base_id = %s
                    """, (id,))
                    updated = cursor.rowcount > 0

                self.connection.commit()
                return updated

            except Error:
                self.connection.rollback()
                return False

    def get_my_tournaments(self, tg_id: int):
        """
        Возвращает первые 10 будущих турниров,
        где пользователь ready=True.
        """

        query = """
            SELECT
                g.id,
                g.base_id,
                g.name,
                g.place,
                g."date_start",
                g."date_end",
                g.is_festival
            FROM ready_to_play r
            JOIN games g
                ON g.base_id = r.game
            WHERE r.player = %s
              AND r.ready = TRUE
              AND g."date_start" >= CURRENT_DATE
            ORDER BY g."date_start"
            LIMIT 10
        """

        return self.fetch_all(query, (tg_id,))

    # =====================================================================
    # PLAYERS
    # =====================================================================

    def add_player_by_tg_id(self, tg_id: int, tg_username: str) -> bool:
        """
        Добавляет игрока, указывая только Telegram ID.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT tg_username
                    FROM players
                    WHERE tg_id = %s
                """, (tg_id, ))

                result = cursor.fetchone()
                if result and result[0] != tg_username:
                    # уже добален

                    cursor.execute("""
                        UPDATE players
                        SET tg_username = %s
                        WHERE tg_id = %s
                    """, (tg_username, tg_id, ))

                    self.connection.commit()
                    return True

                cursor.execute("""
                    INSERT INTO players (tg_id, tg_username)
                    VALUES (%s, %s)
                """, (tg_id, tg_username,))

            self.connection.commit()
            return True

        except Error:
            self.connection.rollback()
            return False

    def get_base_id(self, tg_id: int) -> Optional[int]:
        """
        Возвращает base_id игрока по tg_id.

        Если игрок не найден — None.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT base_id
                    FROM players
                    WHERE tg_id = %s
                """, (tg_id,))

                result = cursor.fetchone()

            if result is None:
                return None

            return result[0]

        except Error:
            self.connection.rollback()
            return None

    def is_admin(self, tg_id: int) -> bool:
        """
        Возвращает значение is_admin по tg_id.

        Если игрок не найден — False.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT is_admin
                    FROM players
                    WHERE tg_id = %s
                """, (tg_id,))

                result = cursor.fetchone()

            if result is None:
                return False

            return bool(result[0])

        except Error:
            self.connection.rollback()
            return False

    def set_rating(self, tg_id: int, value: float) -> bool:
        """
        Изменяет рейтинг игрока по base_id.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE players
                    SET rating = %s
                    WHERE tg_id = %s
                """, (value, tg_id))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    # =====================================================================
    # READY TO PLAY
    # =====================================================================

    def set_ready_to_play(
        self,
        game: int,
        player: int,
        value: bool
    ) -> bool:
        """
        Устанавливает готовность игрока к игре.

        Если запись существует:
            изменяет ready.

        Если записи нет и value=True:
            создаёт запись.

        Если записи нет и value=False:
            ничего не делает.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT id
                    FROM ready_to_play
                    WHERE game = %s AND player = %s
                """, (game, player))

                result = cursor.fetchone()

                if result is not None:
                    cursor.execute("""
                        UPDATE ready_to_play
                        SET ready = %s
                        WHERE game = %s AND player = %s
                    """, (value, game, player))

                    self.connection.commit()
                    return True

                if value:
                    cursor.execute("""
                        INSERT INTO ready_to_play (
                            game,
                            player,
                            ready
                        )
                        VALUES (%s, %s, %s)
                    """, (game, player, value))

                    self.connection.commit()
                    return True

                self.connection.commit()
                return True

        except Error:
            self.connection.rollback()
            return False

    def fetch_all(self, query: str, params=None):
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute(query, params)
                result = cursor.fetchall()

            self.connection.commit()
            return result

        except Error:
            self.connection.rollback()
            raise

    def is_player_in_db(self, tg_id: int) -> bool:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT tg_id
                    FROM players
                    WHERE tg_id = %s
                """, (tg_id,))

                result = cursor.fetchone()
            return result is not None

        except Error:
            self.connection.rollback()
            return False

    def get_future_games(self, limit: int = 10, has_poll: bool=None):
        """
        has_poll:
            None  - все игры;
            True  - poll и poll_id заполнены;
            False - хотя бы одно из poll/poll_id не заполнено.
        """
        try:
            poll = ''
            if has_poll is False:
                poll = ' and (poll_id is NULL or poll is NULL)'
            elif has_poll is True:
                poll = ' and not (poll_id is NULL or poll is NULL)'
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT
                        base_id,
                        name,
                        place,
                        "date_start"
                    FROM games
                    WHERE "date_start" >= CURRENT_DATE""" + poll + """
                    ORDER BY "date_start"
                    LIMIT %s
                """, (limit,))

                result = cursor.fetchall()

            self.connection.commit()
            return result

        except Error:
            self.connection.rollback()
            return []

    def get_game(self, game_id: int):
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT
                        id,
                        base_id,
                        name,
                        place,
                        date_start,
                        date_end,
                        who_added,
                        poll,
                        poll_id,
                        is_festival
                    FROM games
                    WHERE base_id = %s
                """, (game_id,))

                result = cursor.fetchone()

            if result is None:
                return None

            return {
                "id": result[0],
                "base_id": result[1],
                "name": result[2],
                "place": result[3],
                "date_start": result[4],
                "date_end": result[5],
                "who_added": result[6],
                "poll": result[7],
                "poll_id": result[8],
                "is_festival": result[9]
            }

        except Error:
            self.connection.rollback()
            return None

    def set_game_poll(
        self,
        game_id: int,
        message_id: int,
        poll_id: str
    ) -> bool:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE games
                    SET
                        poll = %s,
                        poll_id = %s
                    WHERE base_id = %s
                """, (
                    message_id,
                    poll_id,
                    game_id
                ))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    def get_game_by_poll_id(self, poll_id: str):
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:


                cursor.execute("""
                        SELECT
                            id,
                            base_id,
                            name,
                            place,
                            "date_start",
                            who_added,
                            poll,
                            poll_id,
                            team_notified
                        FROM games
                        WHERE poll_id = %s
                    """, (poll_id,))

                result = cursor.fetchone()

                if result is None:
                    return None

                return {
                    "id": result[0],
                    "base_id": result[1],
                    "name": result[2],
                    "place": result[3],
                    "date_start": result[4],
                    "who_added": result[5],
                    "poll": result[6],
                    "poll_id": result[7],
                    'team_notified': result[8]
                }

        except Error:
            self.connection.rollback()
            return None

    def get_unlinked_players(self, limit: int = 10):
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT
                        id,
                        tg_id,
                        name,
                        surname,
                        tg_username
                    FROM players
                    WHERE tg_id IS NOT NULL AND base_id IS NULL
                    LIMIT %s
                """, (limit,))

                result = cursor.fetchall()

            self.connection.commit()
            return result

        except Error:
            self.connection.rollback()
            return []

    def update_player_by_tg_id(
        self,
        player_id: int,
        base_id: int,
        name: str,
        surname: str,
        patronimyc: str
    ) -> bool:


        """
        Обновляет данные игрока по Telegram ID.
        """
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    UPDATE players
                    SET
                        base_id = %s,
                        name = %s,
                        surname = %s,
                        patronymic = %s
                    WHERE tg_id = %s
                """, (
                    base_id,
                    name,
                    surname,
                    patronimyc,
                    player_id
                ))

                updated = cursor.rowcount > 0

            self.connection.commit()
            return updated

        except Error:
            self.connection.rollback()
            return False

    def get_ready_players_for_game(
        self,
        base_id: int
    ):
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT
                        p.base_id,
                        p.surname,
                        p.name,
                        p.patronymic,
                        (case when p.is_base is True then 'Б' else 'Л' end) flag,
                        tg_username,
                        p.tg_id,
                        p.enable_notifications
                    FROM ready_to_play r
                    JOIN players p
                         ON p.tg_id = r.player
                    WHERE r.game = %s
                    AND r.ready = TRUE
                    ORDER BY p.is_base desc, p.base_id
                """, (base_id,))

                result = cursor.fetchall()

            self.connection.commit()
            return result

        except Error:
            self.connection.rollback()
            return []

    # Проверка числа играющих
    def get_ready_players_count(self, game_base_id: int) -> int:
        try:
            self.check_connection()
            with self.connection.cursor() as cursor:
                cursor.execute("""
                    SELECT COUNT(*)
                    FROM ready_to_play
                    WHERE game = %s
                    AND ready = TRUE
                """, (game_base_id,))

                result = cursor.fetchone()

            self.connection.commit()
            return result[0] if result else 0

        except Error:
            self.connection.rollback()
            return 0

    # =====================================================================
    # CONNECTION
    # =====================================================================

    def close(self) -> None:
        """
        Закрывает соединение с БД.
        """
        if self.connection and not self.connection.closed:
            self.connection.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()